export const list = [
  {
    id: 1,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 50,
    raters: 50,
    participation: '32%',
    expiry_date: '2021-01-01',
    status: 'Active',
  },
  {
    id: 2,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 20,
    raters: 30,
    participation: '12%',
    expiry_date: '2019-08-01',
    status: 'Closed',
  },
  {
    id: 3,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 50,
    raters: 75,
    participation: '12%',
    expiry_date: '2020-01-08',
    status: 'Active',
  },
  {
    id: 4,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 60,
    raters: 25,
    participation: '22%',
    expiry_date: '2020-03-02',
    status: 'Active',
  },
  {
    id: 5,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 50,
    raters: 50,
    participation: '62%',
    expiry_date: '2019-04-01',
    status: 'Active',
  },
  {
    id: 6,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 23,
    raters: 35,
    participation: '12%',
    expiry_date: '2022-03-05',
    status: 'Closed',
  },
  {
    id: 7,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 30,
    raters: 20,
    participation: '82%',
    expiry_date: '2021-09-02',
    status: 'Active',
  },
  {
    id: 8,
    project_name: 'Work Place Survey for Tech Firm 2021',
    company: 'Techytt PTY LTD',
    employees: 20,
    raters: 10,
    participation: '82%',
    expiry_date: '2021-09-02',
    status: 'Active',
  },
];
